server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"
            max-age: 3600
      routes:
        - id: infoquery-service-lb
          uri: lb://infoquery-service
          predicates:
            - Path=/infoquery/**
        - id: user-manager-lb
          uri: lb://user-service
          predicates:
            - Path=/usermanager/**
        - id: enroll-service-lb
          uri: lb://enroll-service
          predicates:
            - Path=/enroll/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'