#server:
#  port: 8001
##  management.endpoint.web.exposure.include = *
#spring:
#  application:
#    name: user-service
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://localhost:3306/academicsystemdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#mybatis:
#  mapperLocations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.lds.springcloud.entities    # 所有Entity别名类所在包
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'